language: node_js
node_js:
  - "4.1.1"
  - "0.12"


os:
  :windowsxp
  :linux
  
before_script:
  - "npm install -g mocha"
  - "npm install istanbul"
  - "npm install coveralls"


script:
  - "istanbul cover _mocha -- -R spec tests/unit/*.js tests/functional/*.js" 
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
